rails-iot/config/routes.rb
Rails.application.routes.draw do

  get 'devices/index'

  controller :stream do 
    get "stream/moon", to: "streams#moon", :as => "moon"
    get "stream/tides/:place", to: "streams#tides", :as => "tides"
    get "stream/forecast/:place", to: "streams#forecast", :as => "temperature"
    get "stream/zip/:id", to: "streams#zip", :as => "zip"
    get "stream", to: "streams#index"
  end

  get 'circuit/sandbox'
  get 'circuit/june_sandbox'

  resources :designs do
    get 'interface' =>"jig#interface"
  end

  namespace :jig do
    get 'designer', :as => "designer"
    get 'generator', :as => "generator"
    get 'bom', :as => "bom"
    get 'form', :as => "form"
  end
  
  get 'jig/interface/:id' => "jig#interface",  :as => "jig_interface"
  devise_for :users
  resources :user, :only => ["show"]

  get 'threejs/height_displacement', :as => "pic2stl"
  get 'threejs/environment', :as => "three_env"
  get 'threejs/plane_box', :as => "plane_box"
  get 'threejs/peg', :as => "peg_designer"
  get 'threejs/weaver', :as => "weaver"

  root 'application#home'
  

end

rails-iot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TESLA - <%= params[:action].humanize %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- <%=params[:controller]%> -->
  <% if params[:controller] != "application" %>
	  <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
	  
	  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
  <% end %>
  
  <script type="text/javascript" src="//use.typekit.net/duw7epu.js"></script>
	<script>
		try { Typekit.load(); } catch (e) {}
	</script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
  <script type="text/javascript">
	  $(function(){
		// PREVENT BROWSER BUMP
		$(window).on('scroll', function(e){
		   scrollAmount = $(this).scrollTop();
		   if(scrollAmount < 1){
		      $(this).scrollTop(1);
		   }
		   if(scrollAmount > $(document).height() - $(window).height()){
		      $(this).scrollTop($(window).height());
		   }
		});
	})
  </script>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/"><b id='logo'>TESLA </b></a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="<%= params[:action] == "home" ? "active" : "" %>">
	        	<a href="/"> Home</a>
	        </li>
	         <li class="<%= params[:action] == "devices" ? "active" : "" %>">
	        	<%= link_to "Devices", devices_index_path %>
	        </li>
	         <li class="<%= params[:action] == "stream" ? "active" : "" %>">
	        	<%= link_to "Streams", stream_path %>
	        </li>
	        <li class="<%= params[:action] == "interface" ? "active" : "" %>">
	        	<%= link_to "Design", jig_interface_path(1) %>
	        </li>

	        
	       <!--  <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	          	
			  <%= glyph "window", :title => "views" %>
	          	Views
	          <span class="caret"></span></a>

	          <ul class="dropdown-menu" role="menu">
	          	<li class="<%= params[:action] == "designer" ? "active" : "" %>">
	        	<%= link_to "Bill of Materials", jig_bom_path, :class=> "navbar-link" %>
		        </li>
		        
	          </ul>
			</li> -->
				  	
	       </ul>
	       <!-- Sign in -->
	   <ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
			<!-- MENU ACCOUNT ITEM  -->
  			<li class="dropdown">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

			  <%= glyph "user", :title => "settings" %>
	          <strong><%= current_user.email %></strong>
	          <span class="caret"></span></a>

	          <ul class="dropdown-menu" role="menu">
	            <li><%= link_to "Upload a model".html_safe, "", :class => 'navbar-link' %> </li>
	             <li class="divider"></li>
	            <li><%= link_to "Your collection".html_safe, :class => 'navbar-link' %> </li>
	            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
	            <li class="divider"></li>
	            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => 'navbar-link'  %></li>
	          </ul>
			</li>
			<!-- END MENU ACCOUNT ITEM -->

			<% else %>
			  <li><% link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
			  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
			<% end %>
	      
		  </ul>
		<!-- end sign in -->

	    </div><!-- /.navbar-collapse -->
	    
	  </div><!-- /.container-fluid -->
	</nav>
	
	  <div class="container">
	  	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
	    <%= yield %>
	  </div>
	

	
<footer class="footer shadow">
  <div class="container">
    <p class="text-muted"> <a href="/"><b>TESLA</b></a>
    	UC Berkeley 2015 </p>
  </div>
</footer>

</body>
</html>

rails-iot/app/views/layouts/full_screen.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proxies - <%= params[:action].humanize %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
  <!--  
  <script type="text/javascript" src="//use.typekit.net/duw7epu.js"></script>
  -->
	<script>
		// try { Typekit.load(); } catch (e) {}
	</script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
  <script type="text/javascript">
	  $(function(){
		// PREVENT BROWSER BUMP
		$(window).on('scroll', function(e){
		   scrollAmount = $(this).scrollTop();
		   if(scrollAmount < 1){
		      $(this).scrollTop(1);
		   }
		   if(scrollAmount > $(document).height() - $(window).height()){
		      $(this).scrollTop($(window).height());
		   }
		});
	})
  </script>
</head>
<body>

	  	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
	    <%= yield %>

</body>
</html>

rails-iot/app/views/layouts/plain.html.erb
<!DOCTYPE html>
<html>
<head>
<title>2.5D - <%= params[:action].humanize %></title>
  <!--<script type="text/javascript" src="//use.typekit.net/duw7epu.js"></script>
	<script>
		try { Typekit.load(); } catch (e) {}
	</script>  -->
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

</head>
<body>
	<%= yield %>
</body>
</html>