rails-iot/config/routes.rb
Rails.application.routes.draw do

  get 'devices/index'

  controller :stream do 
    get "stream/moon", to: "streams#moon", :as => "moon"
    get "stream/tides/:place", to: "streams#tides", :as => "tides"
    get "stream/forecast/:place", to: "streams#forecast", :as => "temperature"
    get "stream/zip/:id", to: "streams#zip", :as => "zip"
    get "stream", to: "streams#index"
  end

  get 'circuit/sandbox'
  get 'circuit/june_sandbox'

  resources :designs do
    get 'interface' =>"jig#interface"
  end

  namespace :jig do
    get 'designer', :as => "designer"
    get 'generator', :as => "generator"
    get 'bom', :as => "bom"
    get 'form', :as => "form"
  end
  
  get 'jig/interface/:id' => "jig#interface",  :as => "jig_interface"
  devise_for :users
  resources :user, :only => ["show"]

  get 'threejs/height_displacement', :as => "pic2stl"
  get 'threejs/environment', :as => "three_env"
  get 'threejs/plane_box', :as => "plane_box"
  get 'threejs/peg', :as => "peg_designer"
  get 'threejs/weaver', :as => "weaver"

  root 'application#home'
  

end

rails-iot/app/models/design.rb
class Design < ActiveRecord::Base
	mount_uploader :json, JsonUploader
end

rails-iot/app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:interface, :show, :edit, :update, :destroy]


  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end

  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    @design.destroy
    respond_to do |format|
      format.html { redirect_to designs_url, notice: 'Design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:name, :bom, :json)
    end
end

rails-iot/app/helpers/designs_helper.rb
module DesignsHelper
end

rails-iot/app/views/designs/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  <%= form_for @design, :html => {:multipart => true} do |f| %>
    <% if @design.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

        <ul>
        <% @design.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class => "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :json %><br>
      <%= f.file_field :json, :class => "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  </div>
</div>

rails-iot/app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

rails-iot/app/views/designs/index.html.erb
<h1>Listing designs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Json</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= design.name %></td>
        <td><%= design.json %></td>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path %>

rails-iot/app/views/designs/new.html.erb
<h1>New design</h1>

<%= render 'form' %>

<%= link_to 'Back', designs_path %>

rails-iot/app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-primary">
<div class="panel-heading">
	
	<h3> 
	<%= link_to designs_path, :class => "btn btn-primary" do %> 
		<span class="glyphicon glyphicon-chevron-left"></span> 
	<% end %>
	WireWrap Design #<%= @design.id %> </h3>
</div>
<div class="panel-body">
	<p class="lead">
	<strong>Name:</strong>
	<%= @design.name %>
	</p>

	<p class="lead">
	<strong>Json:</strong>
	<%= @design.json %>
	</p>
<br>
<div class="btn-group">
	<%= link_to jig_interface_path(@design), :class => "btn btn-primary" do %> 
		<span class="glyphicon glyphicon-pencil"></span> DESIGN
	<% end %>
	<%= link_to edit_design_path(@design), :class => "btn btn-default"   do %> 
		<span class="glyphicon glyphicon-edit"></span> EDIT
	<% end %>
</div>
</div>
</div>